# Generated by Django 4.1 on 2022-12-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forager', '0002_imagerecord_imagespecies_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='album',
        ),
        migrations.RemoveField(
            model_name='species',
            name='album',
        ),
    ]
