# Generated by Django 4.1 on 2023-01-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forager", "0007_alter_imagerecord_record_alter_imagespecies_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
