# Generated by Django 4.1 on 2023-01-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forager', '0008_record_private'),
    ]

    operations = [
    ]
